=== Opetushallitus/hakurekisteri/src/main/resources/perusaste-henkilot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:koodisto="http://service.koodisto.sade.vm.fi/types/koodisto">


    <xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/kunta.xsd"
               namespace="http://service.koodisto.sade.vm.fi/types/koodisto">
    </xs:import>

    <xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/oppilaitosnumero.xsd"
		namespace="http://service.koodisto.sade.vm.fi/types/koodisto">
	</xs:import>

	<xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/kieli.xsd"
		namespace="http://service.koodisto.sade.vm.fi/types/koodisto">
	</xs:import>
	<xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/maatjavaltiot2.xsd"
		namespace="http://service.koodisto.sade.vm.fi/types/koodisto">
	</xs:import>
	<xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/posti.xsd"
		namespace="http://service.koodisto.sade.vm.fi/types/koodisto">
	</xs:import>
	<xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/sukupuoli.xsd" namespace="http://service.koodisto.sade.vm.fi/types/koodisto"></xs:import>
	
	<xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/yksilollistaminen.xsd" namespace="http://service.koodisto.sade.vm.fi/types/koodisto"></xs:import>
	
	<xs:import schemaLocation="https://virkailija.opintopolku.fi/koodisto-service/rest/suorituksentila.xsd" namespace="http://service.koodisto.sade.vm.fi/types/koodisto"></xs:import>
	
	
	<xs:element name="perustiedot" type="perustiedotType" />


	<xs:simpleType name="hetuType">
		<xs:restriction base="xs:string">
			<xs:pattern
				value="[0-9]{6}[-A][0-9]{3}[0123456789ABCDEFHJKLMNPRSTUVWXY]" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="oppijaNumeroType">
		<xs:restriction base="xs:string">
			<xs:pattern value="1\.2\.246\.562\.24\.[0-9]{11}" />
		</xs:restriction>
	</xs:simpleType>


	<xs:complexType name="henkiloType">

		<xs:sequence>
			<xs:choice>
				<xs:element type="hetuType" name="hetu"></xs:element>
				<xs:element type="oppijaNumeroType"
					name="oppijanumero">
				</xs:element>
				<xs:sequence>
					<xs:element type="xs:string"
						name="henkiloTunniste">
					</xs:element>
					<xs:element type="xs:date"
						name="syntymaAika">
					</xs:element>
					<xs:element type="koodisto:sukupuoli"
						name="sukupuoli">
					</xs:element>
				</xs:sequence>
			</xs:choice>
			<xs:element type="koodisto:oppilaitosnumero"
				name="lahtokoulu" maxOccurs="1" minOccurs="1" />
			<xs:element type="xs:string" name="luokka" maxOccurs="1"
				minOccurs="1" />
			
			<xs:element type="xs:string" name="sukunimi" maxOccurs="1"
				minOccurs="1" />
			<xs:element type="xs:string" name="etunimet" maxOccurs="1"
				minOccurs="1" />
			<xs:element type="xs:string" name="kutsumanimi"
				maxOccurs="1" minOccurs="1" />
			<xs:element type="koodisto:kunta" name="kotikunta"
				maxOccurs="1" minOccurs="1" />
			<xs:element type="koodisto:kieli" name="aidinkieli"
				maxOccurs="1" minOccurs="1" />
			<xs:element type="koodisto:maatjavaltiot2"
				name="kansalaisuus" maxOccurs="1" minOccurs="0" />
			<xs:element type="xs:string" name="lahiosoite" maxOccurs="1"
				minOccurs="0" />
			<xs:element type="koodisto:posti" name="postinumero"
				maxOccurs="1" minOccurs="0" />
			<xs:element type="koodisto:maatjavaltiot2" name="maa"
				maxOccurs="1" minOccurs="0" />
			<xs:element type="xs:string" name="matkapuhelin"
				maxOccurs="1" minOccurs="0" />
			<xs:element type="xs:string" name="muuPuhelin" maxOccurs="1"
				minOccurs="0" />
			<xs:choice>
				<xs:group ref="PerusopetuksenKaynyt"></xs:group>
				<xs:group ref="UlkomainenKorvaava"></xs:group>
				<xs:element name="lukio" type="SuoritusType" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element name="ammatillinen" type="SuoritusType" minOccurs="1" maxOccurs="1"></xs:element>
				
			</xs:choice>
			
			
		</xs:sequence>




	</xs:complexType>



	<xs:complexType name="perustiedotType">
		<xs:all>
			<xs:element type="xs:string" name="eranTunniste"
				maxOccurs="1" minOccurs="1" />
			<xs:element type="henkilotType" name="henkilot"
				maxOccurs="1" minOccurs="1" >
					<xs:unique name="uniqueHetu">
  						<xs:selector xpath="henkilo" />
						<xs:field xpath="hetu" />
					</xs:unique>
					<xs:unique name="uniqueOid">
  						<xs:selector xpath="henkilo" />
						<xs:field xpath="oppijanumero" />
					</xs:unique>
					<xs:unique name="uniqueTunniste">
  						<xs:selector xpath="henkilo" />
						<xs:field xpath="henkiloTunniste" />
					</xs:unique>
				
				</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="henkilotType">
		<xs:sequence>
			<xs:element type="henkiloType" name="henkilo"
				maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="SuoritusType">
		<xs:sequence>
			<xs:element name="valmistuminen" type="xs:date" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="myontaja" type="koodisto:oppilaitosnumero" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="suorituskieli" type="koodisto:kieli" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name ="tila" type="koodisto:suorituksentila" maxOccurs="1" minOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="PerusopetusType">
		<xs:complexContent>
			<xs:extension base="SuoritusType">
				<xs:sequence>
					<xs:element name="yksilollistaminen" type="koodisto:yksilollistaminen" minOccurs="0" maxOccurs="1"></xs:element>
				</xs:sequence>
				
			
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:group name="PerusopetuksenKaynyt">
		<xs:sequence>
			<xs:element name="perusopetus" type="PerusopetusType"
				maxOccurs="1" minOccurs="1">
			</xs:element>
			<xs:element name="perusopetuksenlisaopetus"
				type="SuoritusType" maxOccurs="1" minOccurs="0">
			</xs:element>
			<xs:group ref="LisapisteKoulutukset"></xs:group>
		</xs:sequence>
	</xs:group>
	
	<xs:group name="LisapisteKoulutukset">
		<xs:sequence>
			<xs:element name="ammattistartti"
				type="SuoritusType" maxOccurs="1" minOccurs="0">
			</xs:element>
			<xs:element name="valmentava" type="SuoritusType" maxOccurs="1" minOccurs="0"></xs:element>			
			<xs:element name="maahanmuuttajienlukioonvalmistava" type="SuoritusType" maxOccurs="1" minOccurs="0"></xs:element>
			<xs:element name="maahanmuuttajienammvalmistava" type="SuoritusType" maxOccurs="1" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:group>
	
	<xs:group name="UlkomainenKorvaava">
		<xs:sequence>
			<xs:element name="ulkomainen" type="SuoritusType" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:group ref="LisapisteKoulutukset"></xs:group>
		</xs:sequence>
	</xs:group>
	
	
	





</xs:schema>

=== Opetushallitus/hakurekisteri/suoritusrekisteri/src/main/resources/webapp/henkilot-v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<perustiedot xmlns:p="http://service.koodisto.sade.vm.fi/types/koodisto"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="perusaste-henkilot.xsd">
    <eranTunniste>eranTunniste 67</eranTunniste>
    <henkilot>
        <henkilo>
            <hetu>131094-XXXX</hetu>
            <lahtokoulu>05127</lahtokoulu>
            <luokka>9A</luokka>
            <sukunimi>Åädas</sukunimi>
            <etunimet>Juha Jaakko</etunimet>
            <kutsumanimi>Jaakko</kutsumanimi>
            <kotikunta>020</kotikunta>
            <aidinkieli>FI</aidinkieli>
            <kansalaisuus>246</kansalaisuus>
            <lahiosoite>Katu 1 A 1</lahiosoite>
            <postinumero>00100</postinumero>
            <matkapuhelin>040 1234 567</matkapuhelin>
            <muuPuhelin>09 1234 567</muuPuhelin>
            <perusopetus>
                <valmistuminen>2017-06-03</valmistuminen>
                <myontaja>05127</myontaja>
                <suorituskieli>FI</suorituskieli>
                <tila>KESKEN</tila>
                <yksilollistaminen>ALUEITTAIN</yksilollistaminen>
            </perusopetus>
        </henkilo>
        <henkilo>
            <hetu>131094-YYYY</hetu>
            <lahtokoulu>05127</lahtokoulu>
            <luokka>9A</luokka>
            <sukunimi>Åädas</sukunimi>
            <etunimet>Juha Jaakko</etunimet>
            <kutsumanimi>Jaakko</kutsumanimi>
            <kotikunta>020</kotikunta>
            <aidinkieli>FI</aidinkieli>
            <kansalaisuus>246</kansalaisuus>
            <lahiosoite>Katu 1 A 1</lahiosoite>
            <postinumero>00100</postinumero>
            <matkapuhelin>040 1234 567</matkapuhelin>
            <muuPuhelin>09 1234 567</muuPuhelin>
            <valma>
                <valmistuminen>2017-06-03</valmistuminen>
                <myontaja>05127</myontaja>
                <suorituskieli>FI</suorituskieli>
                <tila>KESKEN</tila>
            </valma>
        </henkilo>
        <henkilo>
            <henkiloTunniste>TUNNISTE</henkiloTunniste>
            <syntymaAika>1999-03-32</syntymaAika>
            <sukupuoli>1</sukupuoli>
            <lahtokoulu>05127</lahtokoulu>
            <luokka>9A</luokka>
            <sukunimi>Testinen</sukunimi>
            <etunimet>Pete Jaakko</etunimet>
            <kutsumanimi>Jaakko</kutsumanimi>
            <kotikunta>020</kotikunta>
            <aidinkieli>FI</aidinkieli>
            <kansalaisuus>246</kansalaisuus>
            <lahiosoite>Katu 1 A 1</lahiosoite>
            <postinumero>00100</postinumero>
            <matkapuhelin>040 1234 567</matkapuhelin>
            <muuPuhelin>09 1234 567</muuPuhelin>
            <ulkomainen>
                <valmistuminen>2015-06-03</valmistuminen>
                <myontaja>05127</myontaja>
                <suorituskieli>FI</suorituskieli>
                <tila>KESKEN</tila>
            </ulkomainen>
            <maahanmuuttajienammvalmistava>
                <valmistuminen>2016-06-03</valmistuminen>
                <myontaja>05127</myontaja>
                <suorituskieli>FI</suorituskieli>
                <tila>VALMIS</tila>
            </maahanmuuttajienammvalmistava>
            <valma>
                <valmistuminen>2017-06-03</valmistuminen>
                <myontaja>05127</myontaja>
                <suorituskieli>FI</suorituskieli>
                <tila>KESKEN</tila>
            </valma>
        </henkilo>
        <henkilo>
            <oppijanumero>1.2.246.562.24.esimerkki</oppijanumero>
            <lahtokoulu>05127</lahtokoulu>
            <luokka>9A</luokka>
            <sukunimi>Testinen</sukunimi>
            <etunimet>Mika Jaakko</etunimet>
            <kutsumanimi>Jaakko</kutsumanimi>
            <kotikunta>020</kotikunta>
            <aidinkieli>FI</aidinkieli>
            <kansalaisuus>246</kansalaisuus>
            <lahiosoite>Katu 1 A 1</lahiosoite>
            <postinumero>00100</postinumero>
            <matkapuhelin>040 1234 567</matkapuhelin>
            <muuPuhelin>09 1234 567</muuPuhelin>
            <perusopetus>
                <valmistuminen>2016-06-03</valmistuminen>
                <myontaja>05127</myontaja>
                <suorituskieli>FI</suorituskieli>
                <tila>VALMIS</tila>
                <yksilollistaminen>EI</yksilollistaminen>
            </perusopetus>
            <perusopetuksenlisaopetus>
                <valmistuminen>2017-06-03</valmistuminen>
                <myontaja>05127</myontaja>
                <suorituskieli>FI</suorituskieli>
                <tila>KESKEN</tila>
                <yksilollistaminen>EI</yksilollistaminen>
            </perusopetuksenlisaopetus>
        </henkilo>
    </henkilot>
</perustiedot>
