=== Opetushallitus/hakurekisteri/src/test/resources/perusaste-arvosanat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat"
           xmlns:koodisto="http://service.koodisto.sade.vm.fi/types/koodisto"
           targetNamespace="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat">

    <xs:import namespace="http://service.koodisto.sade.vm.fi/types/koodisto" schemaLocation="common_koodisto.xsd"/>

    <xs:element name="arvosanasiirto" type="arvosanasiirtoType"/>
    <xs:complexType name="LIType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="B32Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="A2Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="arvosanasiirtoType">
        <xs:sequence>
            <xs:element type="xs:string" name="eranTunniste"/>
            <xs:element type="henkilotType" name="henkilot"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="A12Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PSType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="valinnaisetType">
        <xs:sequence>
            <xs:element name="valinnainen" maxOccurs="2" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="10"/>
                        <xs:enumeration value="9"/>
                        <xs:enumeration value="8"/>
                        <xs:enumeration value="7"/>
                        <xs:enumeration value="6"/>
                        <xs:enumeration value="5"/>
                        <xs:enumeration value="4"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="perusopetusType">
        <xs:sequence>
            <xs:element type="koodisto:oppilaitoskoodi" name="myontaja"/>
            <xs:element type="valmistuminenType" name="valmistuminen"/>
            <xs:element type="koodisto:yksilollistaminen" name="yksilollistaminen"/>
            <xs:element type="koodisto:kieli" name="opetuskieli"/>
            <xs:element type="xs:string" name="eiValmistu" minOccurs="0"/>
            <xs:element type="peruopetusArvosanatType" name="arvosanat"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="B1Type">
        <xs:sequence>
            <xs:element type="koodisto:kieli" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KOType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="henkilotType">
        <xs:sequence>
            <xs:element type="henkiloType" name="henkilo" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FIType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="A22Type">
        <xs:sequence>
            <xs:element type="koodisto:kieli" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KSType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KEType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="HIType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AIType">
        <xs:sequence>
            <xs:element type="xs:string" name="tyyppi"/>
            <xs:element name="yleinen" type="yleinenType"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="A1Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="todistuksetType">
        <xs:sequence>
            <xs:element type="perusopetusType" name="perusopetus" minOccurs="0"/>
            <xs:element type="lisaopetusType" name="lisaopetus" minOccurs="0"/>
            <xs:element type="lukioType" name="lukio" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="B22Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TEType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="B3Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="B23Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MUType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="BIType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="lukioType">
        <xs:sequence>
            <xs:element type="xs:string" name="myontaja"/>
            <xs:element type="valmistuminenType" name="valmistuminen"/>
            <xs:element type="xs:string" name="opetuskieli"/>
            <xs:element type="lukioArvosanatType" name="arvosanat"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="valmistuminenType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0123][0-9][.][01][0-9][.][12][0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="lisaopetusType">
        <xs:sequence>
            <xs:element type="xs:string" name="myontaja"/>
            <xs:element type="valmistuminenType" name="valmistuminen"/>
            <xs:element type="xs:string" name="yksilollistaminen"/>
            <xs:element type="xs:string" name="opetuskieli"/>
            <xs:element type="xs:string" name="eiValmistu" minOccurs="0"/>
            <xs:element type="lisaopetusArvosanatType" name="arvosanat"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GEType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="B33Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="B2Type">
        <xs:sequence>
            <xs:element type="xs:string" name="kieli"/>
            <xs:element type="yleinenType" name="yleinen"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FYType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="YHType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KUType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="peruopetusArvosanatType">
        <xs:sequence>
            <xs:element type="AIType" name="AI"/>
            <xs:element type="A1Type" name="A1"/>
            <xs:element type="A12Type" name="A12" minOccurs="0"/>
            <xs:element type="A2Type" name="A2" minOccurs="0"/>
            <xs:element type="A22Type" name="A22" minOccurs="0"/>
            <xs:element type="B1Type" name="B1"/>
            <xs:element type="B2Type" name="B2" minOccurs="0"/>
            <xs:element type="B22Type" name="B22" minOccurs="0"/>
            <xs:element type="B23Type" name="B23" minOccurs="0"/>
            <xs:element type="MAType" name="MA"/>
            <xs:element type="BIType" name="BI"/>
            <xs:element type="GEType" name="GE"/>
            <xs:element type="FYType" name="FY"/>
            <xs:element type="KEType" name="KE"/>
            <xs:element type="TEType" name="TE"/>
            <xs:element type="KTType" name="KT"/>
            <xs:element type="HIType" name="HI"/>
            <xs:element type="YHType" name="YH"/>
            <xs:element type="MUType" name="MU"/>
            <xs:element type="KUType" name="KU"/>
            <xs:element type="KSType" name="KS"/>
            <xs:element type="LIType" name="LI"/>
            <xs:element type="KOType" name="KO"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="lisaopetusArvosanatType">
        <xs:sequence>
            <xs:element type="AIType" name="AI" minOccurs="0"/>
            <xs:element type="A1Type" name="A1" minOccurs="0"/>
            <xs:element type="A12Type" name="A12" minOccurs="0"/>
            <xs:element type="A2Type" name="A2" minOccurs="0"/>
            <xs:element type="A22Type" name="A22" minOccurs="0"/>
            <xs:element type="B1Type" name="B1" minOccurs="0"/>
            <xs:element type="B2Type" name="B2" minOccurs="0"/>
            <xs:element type="B22Type" name="B22" minOccurs="0"/>
            <xs:element type="B23Type" name="B23" minOccurs="0"/>
            <xs:element type="MAType" name="MA" minOccurs="0"/>
            <xs:element type="BIType" name="BI" minOccurs="0"/>
            <xs:element type="GEType" name="GE" minOccurs="0"/>
            <xs:element type="FYType" name="FY" minOccurs="0"/>
            <xs:element type="KEType" name="KE" minOccurs="0"/>
            <xs:element type="TEType" name="TE" minOccurs="0"/>
            <xs:element type="KTType" name="KT" minOccurs="0"/>
            <xs:element type="HIType" name="HI" minOccurs="0"/>
            <xs:element type="YHType" name="YH" minOccurs="0"/>
            <xs:element type="MUType" name="MU" minOccurs="0"/>
            <xs:element type="KUType" name="KU" minOccurs="0"/>
            <xs:element type="KSType" name="KS" minOccurs="0"/>
            <xs:element type="LIType" name="LI" minOccurs="0"/>
            <xs:element type="KOType" name="KO" minOccurs="0"/>
            <xs:element type="PSType" name="PS" minOccurs="0"/>
            <xs:element type="FIType" name="FI" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="lukioArvosanatType">
        <xs:sequence>
            <xs:element type="AIType" name="AI"/>
            <xs:element type="A1Type" name="A1"/>
            <xs:element type="A12Type" name="A12" minOccurs="0"/>
            <xs:element type="A2Type" name="A2" minOccurs="0"/>
            <xs:element type="A22Type" name="A22" minOccurs="0"/>
            <xs:element type="B1Type" name="B1"/>
            <xs:element type="B2Type" name="B2" minOccurs="0"/>
            <xs:element type="B22Type" name="B22" minOccurs="0"/>
            <xs:element type="B23Type" name="B23" minOccurs="0"/>
            <xs:element type="B3Type" name="B3" minOccurs="0"/>
            <xs:element type="B32Type" name="B32" minOccurs="0"/>
            <xs:element type="B33Type" name="B33" minOccurs="0"/>
            <xs:element type="MAType" name="MA"/>
            <xs:element type="BIType" name="BI"/>
            <xs:element type="GEType" name="GE"/>
            <xs:element type="FYType" name="FY"/>
            <xs:element type="KEType" name="KE"/>
            <xs:element type="TEType" name="TE"/>
            <xs:element type="KTType" name="KT"/>
            <xs:element type="HIType" name="HI"/>
            <xs:element type="YHType" name="YH"/>
            <xs:element type="MUType" name="MU"/>
            <xs:element type="KUType" name="KU"/>
            <xs:element type="LIType" name="LI"/>
            <xs:element type="PSType" name="PS"/>
            <xs:element type="FIType" name="FI"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MAType">
        <xs:sequence>
            <xs:element type="yleinenType" name="yleinen"/>
            <xs:element type="valinnaisetType" name="valinnaiset" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="henkiloType">
        <xs:sequence>
            <xs:element type="xs:string" name="henkilonTunniste"/>
            <xs:element name="hetu">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{6}[-A][0-9]{3}[0123456789ABCDEFHJKLMNPRSTUVWXY]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="oppijanumero">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="1\.2\.246\.562\.24\.[0-9]{11}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="todistuksetType" name="todistukset"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="yleinenType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="10"/>
            <xs:enumeration value="9"/>
            <xs:enumeration value="8"/>
            <xs:enumeration value="7"/>
            <xs:enumeration value="6"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="S"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Opetushallitus/hakurekisteri/src/test/resources/perusaste-arvosanat.xml
<?xml version="1.0" encoding="UTF-8"?>
<arvosanasiirto xmlns="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://service.henkilo.sade.vm.fi/types/perusopetus/arvosanat perusaste-arvosanat.xsd">
    <eranTunniste>05127 arvosanat</eranTunniste>
    <henkilot>
        <henkilo>
            <henkilonTunniste>8a08663e-1443-4b39-9056-0694dc0dbe89</henkilonTunniste>
            <hetu>131094-919B</hetu>
            <oppijanumero>1.2.246.562.24.41800604157</oppijanumero>
            <todistukset>
                <perusopetus>
                    <myontaja>05127</myontaja>
                    <valmistuminen>01.06.2014</valmistuminen>
                    <yksilollistaminen>0</yksilollistaminen>
                    <opetuskieli>FI</opetuskieli>
                    <eiValmistu>HYLATTY</eiValmistu>
                    <arvosanat>
                        <AI>
                            <tyyppi>FI_VK</tyyppi>
                            <yleinen>9</yleinen>
                            <valinnaiset>
                                <valinnainen>10</valinnainen>
                                <valinnainen>10</valinnainen>
                            </valinnaiset>
                        </AI>
                        <A1>
                            <kieli>EN</kieli>
                            <yleinen>9</yleinen>
                            <valinnaiset>
                                <valinnainen>10</valinnainen>
                                <valinnainen>9</valinnainen>
                            </valinnaiset>
                        </A1>
                        <A12>
                            <kieli>EN</kieli>
                            <yleinen>9</yleinen>
                            <valinnaiset>
                                <valinnainen>10</valinnainen>
                                <valinnainen>9</valinnainen>
                            </valinnaiset>
                        </A12>
                        <A2>
                            <kieli>EN</kieli>
                            <yleinen>9</yleinen>
                        </A2>
                        <A22>
                            <kieli>DE</kieli>
                            <yleinen>9</yleinen>
                        </A22>
                        <B1>
                            <kieli>SV</kieli>
                            <yleinen>9</yleinen>
                            <valinnaiset>
                                <valinnainen>10</valinnainen>
                                <valinnainen>9</valinnainen>
                            </valinnaiset>
                        </B1>
                        <B2>
                            <kieli>SV</kieli>
                            <yleinen>9</yleinen>
                        </B2>
                        <B22>
                            <kieli>RU</kieli>
                            <yleinen>9</yleinen>
                        </B22>
                        <B23>
                            <kieli>SE</kieli>
                            <yleinen>9</yleinen>
                        </B23>
                        <MA>
                            <yleinen>10</yleinen>
                            <valinnaiset>
                                <valinnainen>9</valinnainen>
                                <valinnainen>6</valinnainen>
                            </valinnaiset>
                        </MA>
                        <BI>
                            <yleinen>10</yleinen>
                            <valinnaiset>
                                <valinnainen>8</valinnainen>
                                <valinnainen>5</valinnainen>
                            </valinnaiset>
                        </BI>
                        <GE>
                            <yleinen>5</yleinen>
                            <valinnaiset>
                                <valinnainen>5</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </GE>
                        <FY>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </FY>
                        <KE>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </KE>
                        <TE>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </TE>
                        <KT>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </KT>
                        <HI>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </HI>
                        <YH>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </YH>
                        <MU>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </MU>
                        <KU>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </KU>
                        <KS>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </KS>
                        <LI>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </LI>
                        <KO>
                            <yleinen>7</yleinen>
                            <valinnaiset>
                                <valinnainen>7</valinnainen>
                                <valinnainen>8</valinnainen>
                            </valinnaiset>
                        </KO>
                    </arvosanat>
                </perusopetus>
                <lisaopetus>
                    <myontaja>05127</myontaja>
                    <valmistuminen>01.06.2015</valmistuminen>
                    <yksilollistaminen>0</yksilollistaminen>
                    <opetuskieli>FI</opetuskieli>
                    <arvosanat>
                        <AI>
                            <tyyppi>FI_VK</tyyppi>
                            <yleinen>6</yleinen>
                        </AI>
                    </arvosanat>
                </lisaopetus>
            </todistukset>
        </henkilo>
        <henkilo>
            <henkilonTunniste>abc-1</henkilonTunniste>
            <hetu>111111-1975</hetu>
            <oppijanumero>1.2.246.562.24.00000000001</oppijanumero>
            <todistukset>
                <lukio>
                    <myontaja>00256</myontaja>
                    <valmistuminen>31.12.2015</valmistuminen>
                    <opetuskieli>FI</opetuskieli>
                    <arvosanat>
                        <AI>
                            <tyyppi>FI_VK</tyyppi>
                            <yleinen>9</yleinen>
                        </AI>
                        <A1>
                            <kieli>EN</kieli>
                            <yleinen>9</yleinen>
                        </A1>
                        <A12>
                            <kieli>EN</kieli>
                            <yleinen>9</yleinen>
                        </A12>
                        <A2>
                            <kieli>EN</kieli>
                            <yleinen>9</yleinen>
                        </A2>
                        <A22>
                            <kieli>DE</kieli>
                            <yleinen>9</yleinen>
                        </A22>
                        <B1>
                            <kieli>SV</kieli>
                            <yleinen>9</yleinen>
                        </B1>
                        <B2>
                            <kieli>SV</kieli>
                            <yleinen>9</yleinen>
                        </B2>
                        <B22>
                            <kieli>RU</kieli>
                            <yleinen>9</yleinen>
                        </B22>
                        <B23>
                            <kieli>SE</kieli>
                            <yleinen>9</yleinen>
